swagger: "2.0"
info:
   title: Bank Argent Transaction API
   description: User Transactions API
   version: "2.0.0"
   termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v2
schemes:
   - http
paths:
   /user/transactions:
      get:
         security:
            - Bearer: []
         tags:
            - Transaction Module
         summary: User transactions
         description: API for fetching user transactions
         consumes:
            - application/json
            - application/xml
         produces:
            - application/json
            - application/xml
         parameters:
            - in: header
              name: Authorization
              description: Attach Bearer JWT token
              type: string
              required: true
         responses:
            "200":
               description: User transactions retrieved successfully
               schema:
                  $ref: "#/definitions/TransactionsGetResponse"
            "400":
               description: Invalid Fields
            "404":
               description: Transaction not found
            "500":
               description: Internal Server Error
   /user/transactions/{transaction_Id}:
      patch:
         security:
            - Bearer: []
         tags:
            - Transaction Module
         summary: User transaction details
         description: API for updating user transaction details
         consumes:
            - application/json
            - application/xml
         produces:
            - application/json
            - application/xml
         parameters:
            - in: header
              name: Authorization
              description: Attach Bearer JWT token
              type: string
              required: true
            - in: path
              name: transaction_Id
              type: string
              description: Attach transaction ID to URL
              required: true
            - in: body
              name: body
              description: Update user profile attributes
              required: true
              schema:
                 $ref: "#/definitions/TransactionPatchBody"
         responses:
            "200":
               description: Transaction details updated successfully
               schema:
                  $ref: "#/definitions/TransactionPatchResponse"
            "400":
               description: Invalid Fields
            "403":
               description: Not authorized to update the transaction
            "500":
               description: Internal Server Error
securityDefinitions:
   Bearer:
      type: apiKey
      name: Authorization
      in: header
definitions:
   TransactionsGetResponse:
      type: object
      properties:
         status:
            type: integer
         message:
            type: string
         body:
            type: object
            properties:
               transaction_Id:
                  type: string
               date:
                  type: string
               description:
                  type: string
               amount:
                  type: number
               balance:
                  type: number
               type:
                  type: string
               category:
                  type: string
               notes:
                  type: string
   TransactionPatchResponse:
      type: object
      properties:
         status:
            type: integer
         message:
            type: string
         body:
            type: object
            properties:
               transaction_Id:
                  type: string
               description:
                  type: string
               category:
                  type: string
               notes:
                  type: string
   TransactionPatchBody:
      type: object
      properties:
         category:
            type: string
         notes:
            type: string
